module DataHand.KeyAliases where
import DataHand.Keys
import Prelude hiding (Left, Right)

-- Aliases for prettier layouts:
ø = NoEvent
lwin = LeftGUI
lapp = Application
qm =  QuestionMark
scol = Semicolon
col = Colon
com = Comma
per = Period
del = Delete
esc = Escape
bktk = BackTick
sqt = Quote
ret = Return
caps = CapsLock
shft = Shift
lctl = Control
dqt = DoubleQuote
bslh = BackSlash
fslh = Slash
nasl = NASLock
lb = LeftBracket
rb = RightBracket
sp = Space
bksp = Backspace
fn = Function
pent = PadEnter
dash = Minus
thr = Three
svn = Seven
eigt = Eight
amp = Ampersand
perc = Percent
dol = Dollar
numl = NumLock
lcb = LeftCurlyBracket
rcb = RightCurlyBracket
lp = LeftParenthesis
rp = RightParenthesis
lab = LeftAngleBracket
rab = RightAngleBracket
ast = Asterisk
eq = Equal
til = Tilde
left = LeftArrow
rite = RightArrow
up = UpArrow
down = DownArrow
pgup = PageUp
pgdn = PageDown
ins = Insert
ps = PrintScreen
