module DataHand.Keys where

data Key = NoEvent
         | ErrorRollOver
         | POSTFail
         | ErrorUndefined
         | A
         | B
         | C
         | D
         | E
         | F
         | G
         | H
         | I
         | J
         | K
         | L
         | M
         | N
         | O
         | P
         | Q
         | R
         | S
         | T
         | U
         | V
         | W
         | X
         | Y
         | Z
         | One
         | Two
         | Three
         | Four
         | Five
         | Six
         | Seven
         | Eight
         | Nine
         | Zero
         | Return
         | Escape
         | Backspace
         | Tab
         | Space
         | Minus
         | Equal
         | LeftBracket
         | RightBracket
         | BackSlash
         | Number -- XXX I think this is Ellipsis or INT2
         | Semicolon
         | Quote
         | BackTick
         | Comma
         | Period
         | Slash
         | CapsLock
         | F1
         | F2
         | F3
         | F4
         | F5
         | F6
         | F7
         | F8
         | F9
         | F10
         | F11
         | F12
         | PrintScreen
         | ScrollLock
         | Pause
         | Insert
         | Home
         | PageUp
         | Delete
         | End
         | PageDown
         | Right
         | Left
         | Down
         | Up
         | NumLock
         | PadSlash
         | PadAsterix
         | PadMinus
         | PadPlus
         | PadEnter
         | Pad1
         | Pad2
         | Pad3
         | Pad4
         | Pad5
         | Pad6
         | Pad7
         | Pad8
         | Pad9
         | Pad0
         | PadPeriod
         | Int1
         | Application
         | Power
         | PadEqual
         | F13
         | F14
         | F15
         | F16
         | F17
         | F18
         | F19
         | F20
         | F21
         | F22
         | F23
         | F24
         | Execute
         | Help
         | Menu
         | Select
         | Stop
         | Again
         | Undo
         | Cut
         | Copy
         | Paste
         | Find
         | Mute
         -- 0x80
         | VolumeUp
         | VolumeDown
         | LockingCapsLock
         | LockingNumLock
         | LockingScrollLock
         | PadComma
         | PadEqualAgain
         | Internat1
         | Internat2
         | Internat3
         | Internat4
         | Internat5
         | Internat6
         | Internat7
         | Internat8
         | Internat9
         | Lang1
         | Lang2
         | Lang3
         | Lang4
         | Lang5
         | Lang6
         | Lang7
         | Lang8
         | Lang9
         | AltErase
         | SysRq
         | Cancel
         | Clear
         | Prior
         -- XXX stops matching up here. next in tabel are Return Pipe Oper Clear/Again
         | Bang
         | At
         | Hash
         | Dollar
         | Percent
         | Caret
         | Ampersand
         | Asterisk
         | LeftParenthesis
         | RightParenthesis
         | ShiftReturn
         | ShiftEscape
         | ShiftBackspace
         | ShiftTab
         | ShiftSpace
         | ShiftMinus
         | Plus
         | LeftCurlyBracket
         | RightCurlyBracket
         | Pipe
         | ShiftNumber -- what is shift+"number"?
         | Colon
         | DoubleQuote
         | Tilde
         | LeftAngleBracket
         | RightAngleBracket
         | QuestionMark
         | ShiftCapsLock
         | DummyBA
         | DummyBB
         | DummyBC
         | DummyBD
         | DummyBE
         | DummyBF
         | DummyC0
         | DummyC1
         | DummyC2
         | DummyC3
         | DummyC4
         | DummyC5
         | DummyC6 | DummyC7 | DummyC8
         | DummyC9 | DummyCA | DummyCB | DummyCC | DummyCD | DummyCE | DummyCF
         | DummyD0 | DummyD1 | DummyD2 | DummyD3 | DummyD4 | DummyD5 | DummyD6 | DummyD7
         | DummyD8 | DummyD9 | DummyDA | DummyDB | DummyDC | DummyDD | DummyDE | DummyDF
         | LeftControl
         | LeftShift
         | LeftAlt
         | LeftGUI
         | RightControl
         | RightShift
         | RightAlt
         | RightGUI
         | DummyE8 | DummyE9 | DummyEA | DummyEB | DummyEC | DummyED | DummyEE | DummyEF
         -- 0xf0 : special datahand keycodes follow
         | Norm --FIXME this is like windows key???
         | NAS
         | NASLock
         | Function
         -- these are different codes from 'regular' keyboard metakeys
         | Shift
         | Control
         | Alt
         deriving (Show, Eq, Ord, Bounded, Enum)
